WHITESPACE = _{ " " | "\t" | "\n" | "\r" }
COMMENT = _{ "//" ~ (!"\n" ~ ANY)* }

program = { SOI ~ function ~ EOI }

function = { "fn" ~ ident ~ "(" ~ ")" ~ "->" ~ type_name ~ block }

block = { "{" ~ statement* ~ "}" }

statement = { return_stmt }

return_stmt = { "return" ~ integer ~ ";" }

type_name = { "i32" }

ident = @{ ASCII_ALPHA ~ (ASCII_ALPHANUMERIC | "_")* }

integer = @{"-"? ~ ASCII_DIGIT+ }