// Generated by Cerberus Typewriter
#include <stdio.h>

int main() {
    int a;
    int b;
    int d;
    int c;

        {
        a = 10;
            {
            b = a;
                {
                d = b;
                /* drop d; (out of scope) */
            }
        }
        c = 11;
            {
            return c;
        }
    }
}
